export default {
  // 上传文件接口
  file: 'other/file',
  // 发送登陆短信验证码
  getSms: 'account/api/getSms',
  // 通过短信验证码登陆
  loginBySms: 'account/api/loginBySms',
  // 判断用户是否为司机
  isDriver: 'member/api/member/isDriver',
  // 获取用户当前司机招募的状态
  applyDriver: 'member/api/member/applyDriver',
  // 发送司机招募资料中手机号的短信验证码
  applySms: 'member/api/member/applySms',
  // 验证司机招募资料中手机号的短信验证码
  applyDriverSmsCode: 'member/api/member/applyDriverSmsCode',
  // 提交司机招募资料信息
  applyInfo: 'member/api/member/applyInfo',
  // 获取司机招募规则阅读状态信息
  applyIsRuleRead: 'member/api/member/applyIsRuleRead',
  // 更新司机招募某一条规则阅读状态并提交相关信息
  applyRuleRead: 'member/api/member/applyRuleRead',
  // 提交加盟车一项数据信息
  saveApplyDriverIntention: 'member/api/member/saveApplyDriverIntention',
  // 加盟司机----添加加盟司机的信息
  addJoinDriver: 'driver/api/intercity/addJoinDriver',
  // 加盟司机----获取加盟司机是否注册过的信息
  joinHaveOrNot: 'driver/api/intercity/joinHaveOrNot',
  // 加盟司机----获取加盟司机审核情况
  getJoinDriverStatus: 'driver/api/intercity/getJoinDriverStatus',
  // 城际司机----获取城际车支持城市列表
  getIntercityCityList: 'driver/api/intercity/queryBranch',
  // 城际司机----个人信息上传
  saveIntercityInfo: 'driver/api/intercity/saveIntercityDriver',
  // 城际司机----获取司机注册过的信息
  getIntercityInfo: 'driver/api/intercity/queryDriver',
  // 城际司机----获取司机审核情况
  getIntercityStatus: 'driver/api/intercity/getDriverStatus',
  // 城际司机----获取车辆品牌型号数据
  getCarBrands: 'driver/api/intercity/brands',
  // 城际司机----加盟司机注册车辆信息接口
  saveCarInfo: 'driver/api/intercity/saveCarInfo',
  // 城际司机----司机需要补充的资料信息
  driverDataSupply: 'driver/api/intercity/driverDataSupply',
  // 城际司机----司机重新提交资料
  updateDriverImgUrl: 'driver/api/intercity/updateDriverImgUrl',
  // 城际司机----修改资料后,重新提交审核
  conserveDriver: 'driver/api/intercity/conserveDriver',
  // 加盟司机----审核拒绝，重新申请
  deleJoinDriver: 'driver/api/intercity/deleJoinDriver'
}
